"""Every third-party module `app/` imports must be a *production* dependency.

This exists because `httpx` spent a release in `[dependency-groups].dev` while
`app/intel/live_enrichment.py` and `app/intel/webhooks.py` imported it. The app booted
fine — both imports are function-level — and live enrichment and watch-rule webhooks
raised `ModuleNotFoundError` in every production install, where the handlers swallowed it.
Nothing in the test suite noticed, because the dev venv has httpx.

The check reads `requirements.txt` (what Docker actually installs, generated by
`task lock`) rather than `pyproject.toml`, so a stale lock is caught too.
"""

from __future__ import annotations

import ast
import re
import sys
from importlib.metadata import packages_distributions
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
APP_DIR = PROJECT_ROOT / "app"
REQUIREMENTS = PROJECT_ROOT / "requirements.txt"

# Modules that are ours, or are provided by the runtime rather than a distribution.
FIRST_PARTY = {"app", "alembic", "init_db", "sync_workflows", "scripts", "tests"}

# Imported under an `except ImportError` that degrades gracefully, with a documented
# fallback. Keep this list short and justified — every other entry here is a dead feature.
OPTIONAL_IMPORTS: dict[str, str] = {
    "psutil": "app/workers/tasks.py falls back to /proc/meminfo for the worker's RAM figure",
}


def _requirement_distributions() -> set[str]:
    """Distribution names in requirements.txt, normalised per PEP 503."""
    names: set[str] = set()
    for raw in REQUIREMENTS.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("-"):
            continue
        # "package[extra]==1.2.3 ; python_version >= ..." → "package"
        name = re.split(r"[\[=<>!~;\s]", line, maxsplit=1)[0]
        if name:
            names.add(_normalise(name))
    return names


def _normalise(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _imported_top_level_modules() -> dict[str, set[str]]:
    """Map top-level module name → set of `app/` files importing it.

    Walks the AST rather than grepping, so function-level imports (the ones that hide this
    class of bug) are found exactly like module-level ones.
    """
    found: dict[str, set[str]] = {}
    for path in sorted(APP_DIR.rglob("*.py")):
        rel = str(path.relative_to(PROJECT_ROOT))
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=rel)
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    found.setdefault(alias.name.split(".")[0], set()).add(rel)
            elif isinstance(node, ast.ImportFrom):
                if node.level:  # relative import — first-party by definition
                    continue
                if node.module:
                    found.setdefault(node.module.split(".")[0], set()).add(rel)
    return found


def test_every_third_party_import_is_a_production_dependency():
    declared = _requirement_distributions()
    assert declared, "requirements.txt parsed to nothing — regenerate with `task lock`"

    module_to_dists = packages_distributions()
    stdlib = sys.stdlib_module_names

    offenders: list[str] = []
    for module, files in sorted(_imported_top_level_modules().items()):
        if module in stdlib or module in FIRST_PARTY or module in OPTIONAL_IMPORTS:
            continue
        dists = module_to_dists.get(module)
        if not dists:
            # Not installed in this venv at all. Either a typo or a genuinely optional
            # import; either way it is not something requirements.txt can satisfy.
            continue
        if any(_normalise(d) in declared for d in dists):
            continue
        where = ", ".join(sorted(files)[:3])
        offenders.append(f"{module} (from {sorted(dists)}) imported by {where}")

    assert not offenders, "third-party imports in app/ that requirements.txt does not install:\n  " + "\n  ".join(offenders)


@pytest.mark.parametrize("module", ["httpx"])
def test_outbound_http_dependency_is_declared(module: str):
    """httpx backs two advertised, documented features."""
    assert _normalise(module) in _requirement_distributions(), f"{module} must be a production dependency"
