"""initial schema

Revision ID: 09db4ba71a7c
Revises:
Create Date: 2026-04-12 10:01:25.802840
"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa

from alembic import op

revision: str = "09db4ba71a7c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backgroundtask",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", name="backgroundtaskstatus"), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "entity",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("job_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value", "entity_type", name="uq_entity_value_type"),
    )
    op.create_index(op.f("ix_entity_entity_type"), "entity", ["entity_type"], unique=False)
    op.create_table(
        "logfile",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("stored_filename", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("log_type", sa.Enum("EVTX", "JSON_EVTX", "JSON_WINLOGBEAT", "AUDITD", "SYSLOG", "UNKNOWN", name="logtype"), nullable=False),
        sa.Column("detected_type", sa.Enum("EVTX", "JSON_EVTX", "JSON_WINLOGBEAT", "AUDITD", "SYSLOG", "UNKNOWN", name="logtype"), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("uploader_ip", sa.String(length=45), nullable=True),
        sa.Column("tlsh_hash", sa.String(length=72), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_filename"),
    )
    op.create_index(op.f("ix_logfile_sha256"), "logfile", ["sha256"], unique=False)
    op.create_index(op.f("ix_logfile_tlsh_hash"), "logfile", ["tlsh_hash"], unique=False)
    op.create_table(
        "sitesettings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parallel_execution", sa.Boolean(), nullable=False),
        sa.Column("max_finding_details", sa.Integer(), nullable=False),
        sa.Column("show_mitre_heatmap", sa.Boolean(), nullable=False),
        sa.Column("show_event_timeline", sa.Boolean(), nullable=False),
        sa.Column("show_entities", sa.Boolean(), nullable=False),
        sa.Column("show_threat_detection", sa.Boolean(), nullable=False),
        sa.Column("demo_mode", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "threat_indicator",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category_key", sa.String(length=50), nullable=False),
        sa.Column("tag", sa.String(length=200), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("job_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_key", "tag", name="uq_threat_indicator_cat_tag"),
    )
    op.create_index(op.f("ix_threat_indicator_category_key"), "threat_indicator", ["category_key"], unique=False)
    op.create_table(
        "user",
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "workflowdef",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("log_types", sa.Text(), nullable=False),
        sa.Column("tasks_yaml", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "analysisjob",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("workflow_id", sa.Integer(), nullable=False),
        sa.Column("submitted_by_user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
        sa.Column("submitter_ip", sa.String(length=45), nullable=True),
        sa.Column("status", sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", "PARTIAL", name="jobstatus"), nullable=False),
        sa.Column("score_ratio", sa.String(length=20), nullable=True),
        sa.Column("total_findings", sa.Integer(), nullable=True),
        sa.Column("severity_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("analytics_json", sa.Text(), nullable=True),
        sa.Column("is_private", sa.Boolean(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["logfile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflowdef.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analysisjob_created_at"), "analysisjob", ["created_at"], unique=False)
    op.create_index(op.f("ix_analysisjob_file_id"), "analysisjob", ["file_id"], unique=False)
    op.create_index(op.f("ix_analysisjob_status"), "analysisjob", ["status"], unique=False)
    op.create_index(op.f("ix_analysisjob_submitted_by_user_id"), "analysisjob", ["submitted_by_user_id"], unique=False)
    op.create_index(op.f("ix_analysisjob_workflow_id"), "analysisjob", ["workflow_id"], unique=False)
    op.create_table(
        "entity_job_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["analysisjob.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_id", "job_id", name="uq_entity_job"),
    )
    op.create_index(op.f("ix_entity_job_link_entity_id"), "entity_job_link", ["entity_id"], unique=False)
    op.create_index(op.f("ix_entity_job_link_job_id"), "entity_job_link", ["job_id"], unique=False)
    op.create_table(
        "taskresult",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", "SKIPPED", name="taskstatus"), nullable=False),
        sa.Column("findings_count", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("log_output", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["analysisjob.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_taskresult_job_id"), "taskresult", ["job_id"], unique=False)
    op.create_table(
        "threat_indicator_job_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("indicator_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["threat_indicator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["analysisjob.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("indicator_id", "job_id", name="uq_threat_indicator_job"),
    )
    op.create_index(op.f("ix_threat_indicator_job_link_indicator_id"), "threat_indicator_job_link", ["indicator_id"], unique=False)
    op.create_index(op.f("ix_threat_indicator_job_link_job_id"), "threat_indicator_job_link", ["job_id"], unique=False)
    op.create_table(
        "finding",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_result_id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.String(length=100), nullable=True),
        sa.Column("rule_name", sa.String(length=500), nullable=False),
        sa.Column("severity", sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL", name="severity"), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("rule_signature", sa.String(length=200), nullable=True),
        sa.Column("rule_content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_result_id"],
            ["taskresult.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_finding_rule_signature"), "finding", ["rule_signature"], unique=False)
    op.create_index(op.f("ix_finding_task_result_id"), "finding", ["task_result_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_finding_task_result_id"), table_name="finding")
    op.drop_index(op.f("ix_finding_rule_signature"), table_name="finding")
    op.drop_table("finding")
    op.drop_index(op.f("ix_threat_indicator_job_link_job_id"), table_name="threat_indicator_job_link")
    op.drop_index(op.f("ix_threat_indicator_job_link_indicator_id"), table_name="threat_indicator_job_link")
    op.drop_table("threat_indicator_job_link")
    op.drop_index(op.f("ix_taskresult_job_id"), table_name="taskresult")
    op.drop_table("taskresult")
    op.drop_index(op.f("ix_entity_job_link_job_id"), table_name="entity_job_link")
    op.drop_index(op.f("ix_entity_job_link_entity_id"), table_name="entity_job_link")
    op.drop_table("entity_job_link")
    op.drop_index(op.f("ix_analysisjob_workflow_id"), table_name="analysisjob")
    op.drop_index(op.f("ix_analysisjob_submitted_by_user_id"), table_name="analysisjob")
    op.drop_index(op.f("ix_analysisjob_status"), table_name="analysisjob")
    op.drop_index(op.f("ix_analysisjob_file_id"), table_name="analysisjob")
    op.drop_index(op.f("ix_analysisjob_created_at"), table_name="analysisjob")
    op.drop_table("analysisjob")
    op.drop_table("workflowdef")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_threat_indicator_category_key"), table_name="threat_indicator")
    op.drop_table("threat_indicator")
    op.drop_table("sitesettings")
    op.drop_index(op.f("ix_logfile_tlsh_hash"), table_name="logfile")
    op.drop_index(op.f("ix_logfile_sha256"), table_name="logfile")
    op.drop_table("logfile")
    op.drop_index(op.f("ix_entity_entity_type"), table_name="entity")
    op.drop_table("entity")
    op.drop_table("backgroundtask")
    # ### end Alembic commands ###
