"""task control: BackgroundTask gains kind/huey_task_id/requester/heartbeat, plus CANCELLED

The autogenerated draft again proposed dropping the indexes created imperatively in
`app/database.py` — they are invisible to `compare_metadata`, not drift. Removed.

On the enum: rendering the DDL shows `Column(Enum(BackgroundTaskStatus))` produces a bare
`status VARCHAR(9)` on SQLite with **no CHECK constraint** (SQLAlchemy has defaulted
`create_constraint=False` since 1.4), and `len("CANCELLED") == 9 == len("COMPLETED")` — so
the SQLite half of adding a member is a genuine no-op and `compare_metadata` sees the same
type on both sides. PostgreSQL has a real enum type and needs `ALTER TYPE ... ADD VALUE`,
which must run outside the migration's transaction and before any statement uses the label.
This follows `b7c4e92d1a63_add_cancelled_status.py`, not `b7e4f2a91c38`, whose
`alter_column(type_=sa.Enum(...))` approach emits a no-op cast on PostgreSQL and never
teaches the type the new value.

Revision ID: 2140405f6ea4
Revises: 6ee7dc2589d7
Create Date: 2026-08-15 23:40:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2140405f6ea4"
down_revision: str | None = "6ee7dc2589d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        # Its own transaction, before the DDL below: PostgreSQL refuses to use a new enum
        # label in the transaction that added it.
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE backgroundtaskstatus ADD VALUE IF NOT EXISTS 'CANCELLED'")

    with op.batch_alter_table("backgroundtask", schema=None) as batch_op:
        batch_op.add_column(sa.Column("kind", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("huey_task_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("requested_by_label", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("target_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("heartbeat_at", sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f("ix_backgroundtask_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_backgroundtask_huey_task_id"), ["huey_task_id"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("backgroundtask", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backgroundtask_huey_task_id"))
        batch_op.drop_index(batch_op.f("ix_backgroundtask_kind"))
        batch_op.drop_column("heartbeat_at")
        batch_op.drop_column("target_id")
        batch_op.drop_column("requested_by_label")
        batch_op.drop_column("huey_task_id")
        batch_op.drop_column("kind")

    # A row already cancelled has no representation in the old set; fold it into FAILED so
    # the column stays readable if someone downgrades. PostgreSQL cannot drop an enum
    # value, and an unused extra member is harmless.
    op.execute("UPDATE backgroundtask SET status = 'FAILED' WHERE status = 'CANCELLED'")
