"""Index the hot visibility and roll-up columns

Eight indexes, all additive — no data is touched and the downgrade is a clean drop.

They cover the predicates the application runs most and had no index for:

* ``analysisjob.is_private`` — part of ``visible_job_filter``, i.e. essentially every job
  query the application makes.
* ``investigation_case.is_shared`` / ``.created_by_user_id`` — both legs of
  ``visible_case_filter``; neither was indexed.
* ``entity.last_seen_at`` — the Intel dashboard's default sort and the IOC feed's
  ordering, previously a filesort over the whole entity table.
* ``finding (task_result_id, severity)`` and ``(task_result_id, rule_name)`` — the
  ``GROUP BY`` keys of every per-job and per-case roll-up, on the largest table in the
  schema. Led by ``task_result_id`` so they also serve the lookup each roll-up starts from.
* ``case_entity_link`` / ``case_job_link (case_id, added_at)`` — the paged case listings'
  access path verbatim, mirroring ``ix_comment_case_created``.

On a large instance the two ``finding`` indexes are the slow part of this migration; it is
still an online, additive operation.

Revision ID: 218f0f8db869
Revises: d5e82f13c740
Create Date: 2026-08-09 19:41:30.005780
"""
from typing import Sequence, Union

from alembic import op

revision: str = '218f0f8db869'
down_revision: Union[str, None] = 'd5e82f13c740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysisjob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysisjob_is_private'), ['is_private'], unique=False)

    with op.batch_alter_table('case_entity_link', schema=None) as batch_op:
        batch_op.create_index('ix_case_entity_link_case_added', ['case_id', 'added_at'], unique=False)

    with op.batch_alter_table('case_job_link', schema=None) as batch_op:
        batch_op.create_index('ix_case_job_link_case_added', ['case_id', 'added_at'], unique=False)

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.create_index('ix_entity_last_seen', ['last_seen_at'], unique=False)

    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index('ix_finding_task_rule_name', ['task_result_id', 'rule_name'], unique=False)
        batch_op.create_index('ix_finding_task_severity', ['task_result_id', 'severity'], unique=False)

    with op.batch_alter_table('investigation_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_case_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigation_case_is_shared'), ['is_shared'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigation_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_case_is_shared'))
        batch_op.drop_index(batch_op.f('ix_investigation_case_created_by_user_id'))

    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index('ix_finding_task_severity')
        batch_op.drop_index('ix_finding_task_rule_name')

    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_last_seen')

    with op.batch_alter_table('case_job_link', schema=None) as batch_op:
        batch_op.drop_index('ix_case_job_link_case_added')

    with op.batch_alter_table('case_entity_link', schema=None) as batch_op:
        batch_op.drop_index('ix_case_entity_link_case_added')

    with op.batch_alter_table('analysisjob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysisjob_is_private'))

    # ### end Alembic commands ###
