"""activity: which categories to capture

Nullable, and NULL means "all of them" — the useful default for an operator who has just
turned capture on and has not yet formed an opinion about which buckets they want.

The autogenerated draft again proposed dropping the indexes `app/database.py` creates
imperatively; removed, as in every revision since 6ee7dc2589d7.

Revision ID: 32229ad1d2b0
Revises: 42a42671aca3
Create Date: 2026-08-16 10:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "32229ad1d2b0"
down_revision: str | None = "42a42671aca3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("sitesettings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("activity_categories", sa.String(length=200), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("sitesettings", schema=None) as batch_op:
        batch_op.drop_column("activity_categories")
