"""tag definitions

A tag can now exist before anything carries it. `EntityTag` is the association and cannot
represent an unused tag, so previously the only way to create one was to apply it — which
makes "agree a vocabulary, then label against it" impossible.

Revision ID: 397f15ab8d0a
Revises: 23fc66a016c9
NOTE: alembic autogenerate also proposed dropping ix_analysisjob_*, ix_backgroundtask_*,
ix_entity_type, ix_entity_value and ix_finding_rule_sig_id. Those are created by
`app/database.py` outside the ORM metadata, so they look like drift to `compare_metadata`
but are load-bearing in production. They are deliberately not dropped here.

Create Date: 2026-08-07 12:26:52.374090
"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

revision: str = '397f15ab8d0a'
down_revision: Union[str, None] = '23fc66a016c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_definition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), server_default='gray', nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_by_user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_definition_tag'), ['tag'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_definition_tag'))

    op.drop_table('tag_definition')
    # ### end Alembic commands ###
