"""storage: the nullable output-retention override

Nullable is the design, not an oversight. NULL means "use JOB_OUTPUT_RETENTION_DAYS", so
the environment variable keeps the exact meaning it gained in 0.9.1 and an operator who
sets it in `.env` is never silently ignored — `app/retention.py` resolves the pair and
reports which one won.

The autogenerated draft again proposed dropping the indexes `app/database.py` creates
imperatively. Removed; they are invisible to `compare_metadata`, not drift.

Revision ID: 42a42671aca3
Revises: 2140405f6ea4
Create Date: 2026-08-16 00:20:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "42a42671aca3"
down_revision: str | None = "2140405f6ea4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("sitesettings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_output_retention_days_override", sa.Integer(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("sitesettings", schema=None) as batch_op:
        batch_op.drop_column("job_output_retention_days_override")
