"""activity log: the activity_event table and its capture switch

The autogenerated draft also proposed dropping eight indexes on `analysisjob`,
`backgroundtask`, `entity` and `finding`. Those are **not** drift: they are created
imperatively in `app/database.py` rather than declared on the models, so autogenerate
cannot see them and reads them as removals. Dropping them would quietly take out the
index behind the jobs list and the entity dashboard. They are removed from this revision
deliberately — check for the same false positive on the next autogenerate.

Revision ID: 6ee7dc2589d7
Revises: c3d8e5f10a47
Create Date: 2026-08-15 22:52:12.062408
"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "6ee7dc2589d7"
down_revision: str | None = "c3d8e5f10a47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "activity_event",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("actor_user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
        sa.Column("actor_label", sa.String(length=255), nullable=False),
        sa.Column("actor_ip", sa.String(length=45), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_activity_event_action"), ["action"], unique=False)
        batch_op.create_index("ix_activity_event_actor_created", ["actor_user_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_activity_event_category"), ["category"], unique=False)
        batch_op.create_index("ix_activity_event_category_created", ["category", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_activity_event_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_activity_event_target", ["target_type", "target_id"], unique=False)

    # server_default so the NOT NULL holds for the existing single row; the model default
    # takes over for anything created afterwards.
    with op.batch_alter_table("sitesettings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("activity_log_enabled", sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    with op.batch_alter_table("sitesettings", schema=None) as batch_op:
        batch_op.drop_column("activity_log_enabled")

    with op.batch_alter_table("activity_event", schema=None) as batch_op:
        batch_op.drop_index("ix_activity_event_target")
        batch_op.drop_index(batch_op.f("ix_activity_event_created_at"))
        batch_op.drop_index("ix_activity_event_category_created")
        batch_op.drop_index(batch_op.f("ix_activity_event_category"))
        batch_op.drop_index("ix_activity_event_actor_created")
        batch_op.drop_index(batch_op.f("ix_activity_event_action"))

    op.drop_table("activity_event")
