#!/usr/bin/env python3
"""
Generate one .env per fleet host, from one set of shared secrets.

The manual path (`./logstotal deploy:env-scaffold`) writes two *templates* with placeholder
VPN addresses and one worker file for N workers, which the operator then hand-edits
seven times and copies by hand. This writes the real thing: a file per host, every
cross-host value already resolved, each worker with its own name and address.

    python3 scripts/deploy_fleet_env.py --hosts cp.example.com,w1.example.com

Secrets are generated ONCE and never rotated. They live in `deploy-envs/secrets.json`
(mode 0600); a re-run loads them, so running this again is a no-op that will not log
every session out or leave workers authenticating against the old database password.
Unmanaged keys in an existing file are preserved, so a hand-added setting survives.

Stdlib-only, run through lib/common.sh::run_py — the `gen_secrets.py` / `proxy_enable.py`
/ `backup_lifecycle.py` shape. It imports both of those rather than restating them:
`generate()` is where the secret recipes live, and `apply_proxy_settings()` is the one
implementation of "turn HTTPS on".
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from gen_secrets import _is_placeholder, generate  # noqa: E402
from proxy_enable import apply_basic_auth, apply_proxy_settings  # noqa: E402

STATE_VERSION = 1
DEFAULT_OUT_DIR = "deploy-envs"
DEFAULT_STATE = "deploy-envs/secrets.json"
DEFAULT_ADDRESSES = "deploy-envs/vpn.json"

# The eight values every host in a fleet must agree on. SECRET_KEY signs sessions;
# the rest are service credentials embedded in the workers' connection URLs. A
# mismatch on any of them surfaces as jobs stuck in `pending`, which is the least
# diagnosable failure this deployment has.
SHARED_SECRET_KEYS = (
    "SECRET_KEY",
    "ADMIN_PASSWORD",
    "POSTGRES_PASSWORD",
    "REDIS_PASSWORD",
    "S3_ACCESS_KEY",
    "S3_SECRET_KEY",
    "GARAGE_RPC_SECRET",
    "GARAGE_ADMIN_TOKEN",
)

# Garage refuses nothing when these are absent — it falls back to a built-in default
# and prints a warning nobody reads, so a fleet that omits them runs bundled S3 on the
# shipped RPC secret.
S3_BUCKET = "logstotal"
S3_REGION = "logstotal"

# Where set_key() appends the keys it manages. A literal that every .env this has ever
# written already carries, so it never changes wording: a new one would miss those files
# and stamp a second marker into each.
MARKER = "# ── generated by task deploy:env ──"


class GeneratorError(Exception):
    """A configuration problem the operator has to resolve. Carries the fix."""


# ── Hosts ────────────────────────────────────────────────────────────────────


def slugify(entry: str) -> str:
    """A stable, collision-free filename for a host entry.

    Chosen over `control-plane.env` / `worker-01.env` because the push step needs a
    total function from host to file, and positional names silently point at the wrong
    machine the moment the host list is reordered.
    """
    bare = entry.split("@", 1)[-1]
    return re.sub(r"[^A-Za-z0-9._-]", "_", bare) or "host"


def parse_hosts(raw: str) -> list[dict[str, str]]:
    entries = [part.strip() for part in raw.split(",")]
    entries = [e for e in entries if e]
    if not entries:
        raise GeneratorError("No hosts given. Pass --hosts cp.example.com,w1.example.com")
    hosts: list[dict[str, str]] = []
    for index, entry in enumerate(entries):
        hosts.append(
            {
                "entry": entry,
                "slug": slugify(entry),
                "role": "control-plane" if index == 0 else "worker",
            }
        )
    slugs = [h["slug"] for h in hosts]
    duplicates = sorted({s for s in slugs if slugs.count(s) > 1})
    if duplicates:
        raise GeneratorError(f"Two hosts resolve to the same env file: {duplicates}. Give them distinct names.")
    return hosts


def worker_name(entry: str, index: int) -> str:
    """A readable label for /admin/workers — the host's short name, or its position.

    An IP address has no short name worth showing, and `10.0.0.7` as a WORKER_NAME
    reads like a bug, so those fall back to worker-NN.
    """
    bare = entry.split("@", 1)[-1]
    if re.fullmatch(r"[0-9.]+|[0-9a-fA-F:]+", bare):
        return f"worker-{index:02d}"
    short = bare.split(".", 1)[0]
    cleaned = re.sub(r"[^A-Za-z0-9_-]", "-", short).strip("-")
    return cleaned or f"worker-{index:02d}"


# ── Addresses ────────────────────────────────────────────────────────────────


def resolve_addresses(
    hosts: list[dict[str, str]],
    *,
    cp_address: str | None,
    vpn: dict[str, str] | None,
) -> tuple[dict[str, str], list[str]]:
    """Map each host entry to the address the *other* hosts should use for it.

    Order: an explicit --cp-address, then a VPN map written by `./logstotal deploy:vpn`, then
    the host entry itself. The last is what makes a fleet work with no configuration at
    all, and it is also the one that binds Redis/PostgreSQL/Garage to a routable
    address — so it returns a warning rather than doing it quietly.
    """
    warnings: list[str] = []
    vpn = vpn or {}
    addresses: dict[str, str] = {}
    for host in hosts:
        entry = host["entry"]
        addresses[entry] = vpn.get(entry) or entry.split("@", 1)[-1]

    control_plane = hosts[0]["entry"]
    if cp_address:
        addresses[control_plane] = cp_address
    elif control_plane in vpn:
        pass  # already taken from the VPN map above
    elif control_plane == "local":
        raise GeneratorError(
            "The control plane is 'local', so the address workers should use for it cannot be "
            "derived from the host list. Set DEPLOY_CP_ADDRESS=<the address workers will reach "
            "it on>, or run: ./logstotal deploy:vpn"
        )
    else:
        warnings.append(
            f"No VPN address map and no DEPLOY_CP_ADDRESS: workers will reach the control plane at "
            f"{addresses[control_plane]}, which means Redis, PostgreSQL and Garage are bound to a "
            f"routable address and protected only by their passwords."
        )
        warnings.append("Firewall those ports to the worker addresses, or set DEPLOY_VPN=wireconf.")

    for host in hosts[1:]:
        if host["entry"] == "local" and host["entry"] not in vpn:
            addresses[host["entry"]] = "127.0.0.1"
    return addresses, warnings


def is_ip_literal(value: str) -> bool:
    return bool(re.fullmatch(r"\d{1,3}(\.\d{1,3}){3}", value)) or ":" in value


def bind_address_for(cp_address: str) -> tuple[str, list[str]]:
    """The address the control plane BINDS its relays to — not the one workers dial.

    `REDIS_EXPOSE` and friends are interpolated straight into a compose `ports:` entry,
    and Docker refuses a hostname there: `invalid IP address: cp.example.com`, which
    fails the deploy at `./logstotal docker:up` with nothing pointing at the env file that
    caused it. With a VPN the two are the same address and this is invisible; without
    one, the host list holds a name.

    0.0.0.0 rather than resolving the name, because what DNS says about a host and what
    that host can bind are different questions — behind NAT the public A record is not
    on any local interface. It binds every interface, which is exactly what the
    exposure warning already tells the operator is happening.
    """
    if is_ip_literal(cp_address):
        return cp_address, []
    return "0.0.0.0", [  # noqa: S104 - a bind address, deliberately every interface
        f"The control plane is named '{cp_address}', which Docker cannot use as a bind address, "
        "so Redis, PostgreSQL and Garage are bound to 0.0.0.0 — every interface. "
        "Set DEPLOY_CP_ADDRESS to an IP, or run ./logstotal deploy:vpn."
    ]


# ── Secrets ──────────────────────────────────────────────────────────────────


def load_state(state_path: Path) -> dict[str, str]:
    if not state_path.exists():
        return {}
    try:
        blob = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise GeneratorError(f"{state_path} is not readable JSON ({exc}). Move it aside to start fresh.") from exc
    secrets_blob = blob.get("secrets", {})
    return {k: v for k, v in secrets_blob.items() if isinstance(v, str) and v}


def harvest(text: str, keys: tuple[str, ...]) -> dict[str, str]:
    """Pull real (non-placeholder) values for KEYS out of an env file body."""
    found: dict[str, str] = {}
    for key in keys:
        match = re.search(rf"^{re.escape(key)}=(.*)$", text, flags=re.M)
        if match and not _is_placeholder(match.group(1)):
            found[key] = match.group(1).strip()
    return found


def resolve_secrets(*, state: dict[str, str], seed_files: list[Path], force: bool) -> tuple[dict[str, str], list[str]]:
    """State first, then any seed file, then freshly generated. Never rotates.

    The seed files matter for two migrations: a single-host deployment growing into a
    fleet (its `.env` already has a SECRET_KEY every session depends on), and a fleet
    scaffolded with the two-file `./logstotal deploy:env-scaffold`.
    """
    resolved: dict[str, str] = {} if force else dict(state)
    sources: list[str] = []
    if resolved:
        sources.append("secrets.json")
    if not force:
        for seed in seed_files:
            if len(resolved) == len(SHARED_SECRET_KEYS):
                break
            if not seed.exists():
                continue
            harvested = harvest(seed.read_text(encoding="utf-8"), SHARED_SECRET_KEYS)
            new = {k: v for k, v in harvested.items() if k not in resolved}
            if new:
                resolved.update(new)
                sources.append(str(seed))
    fresh = generate()
    missing = [k for k in SHARED_SECRET_KEYS if k not in resolved]
    for key in missing:
        resolved[key] = fresh[key]
    if missing:
        sources.append(f"generated ({len(missing)})")
    return {k: resolved[k] for k in SHARED_SECRET_KEYS}, sources


def write_state(state_path: Path, secrets_map: dict[str, str]) -> None:
    state_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {"version": STATE_VERSION, "secrets": secrets_map}
    state_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    state_path.chmod(0o600)


# ── Env bodies ───────────────────────────────────────────────────────────────


def control_plane_keys(secrets_map: dict[str, str], *, admin_email: str, bind_address: str, proxied: bool, proxy_tls: str = "acme") -> dict[str, str]:
    return {
        "SECRET_KEY": secrets_map["SECRET_KEY"],
        "ADMIN_EMAIL": admin_email,
        "ADMIN_PASSWORD": secrets_map["ADMIN_PASSWORD"],
        "COMPOSE_PROFILES": "postgres,s3,workers",
        "POSTGRES_PASSWORD": secrets_map["POSTGRES_PASSWORD"],
        "REDIS_PASSWORD": secrets_map["REDIS_PASSWORD"],
        "STORAGE_BACKEND": "s3",
        "S3_BUCKET": S3_BUCKET,
        "S3_ACCESS_KEY": secrets_map["S3_ACCESS_KEY"],
        "S3_SECRET_KEY": secrets_map["S3_SECRET_KEY"],
        "S3_REGION": S3_REGION,
        "GARAGE_RPC_SECRET": secrets_map["GARAGE_RPC_SECRET"],
        "GARAGE_ADMIN_TOKEN": secrets_map["GARAGE_ADMIN_TOKEN"],
        "REDIS_EXPOSE": f"{bind_address}:6379",
        "POSTGRES_EXPOSE": f"{bind_address}:5432",
        "GARAGE_EXPOSE": f"{bind_address}:3900",
        # A fresh control plane is reached over plain HTTP on the private network, and the
        # auth cookie is Secure-flagged by default — so login succeeds server-side, the
        # browser drops the cookie, and it reads as "the password is wrong". Caddy in front
        # is exactly the moment that stops being true — unless it is in front on plain HTTP
        # (PROXY_TLS=off), which is why the proxy branch asks about the mode and not just
        # about the profile.
        "COOKIE_INSECURE": "false" if (proxied and proxy_tls != "off") else "true",
    }


def worker_keys(secrets_map: dict[str, str], *, cp_address: str, name: str, address: str, huey_workers: int) -> dict[str, str]:
    pg = secrets_map["POSTGRES_PASSWORD"]
    return {
        "SECRET_KEY": secrets_map["SECRET_KEY"],
        "WORKER_NAME": name,
        "WORKER_IP": address,
        "DATABASE_URL": f"postgresql+asyncpg://logstotal:{pg}@{cp_address}:5432/logstotal",
        "SYNC_DATABASE_URL": f"postgresql+psycopg2://logstotal:{pg}@{cp_address}:5432/logstotal",
        "REDIS_URL": f"redis://:{secrets_map['REDIS_PASSWORD']}@{cp_address}:6379",
        "STORAGE_BACKEND": "s3",
        "S3_ENDPOINT": f"http://{cp_address}:3900",
        "S3_BUCKET": S3_BUCKET,
        "S3_ACCESS_KEY": secrets_map["S3_ACCESS_KEY"],
        "S3_SECRET_KEY": secrets_map["S3_SECRET_KEY"],
        "S3_REGION": S3_REGION,
        "HUEY_WORKERS": str(huey_workers),
    }


def set_key(text: str, key: str, value: str) -> str:
    """Replace KEY's value in place, or append it under the generated-by marker.

    In-place replacement is what preserves an operator's hand-added keys and their
    comments across a re-run — the alternative, rewriting the whole file, turns every
    re-run of the one command into a silent config wipe.
    """
    pattern = rf"^{re.escape(key)}=.*$"
    if re.search(pattern, text, flags=re.M):
        return re.sub(pattern, lambda _m: f"{key}={value}", text, count=1, flags=re.M)
    if MARKER not in text:
        if text and not text.endswith("\n"):
            text += "\n"
        text += f"\n{MARKER}\n"
    return text.rstrip("\n") + f"\n{key}={value}\n"


def render_host_env(existing: str, *, role: str, entry: str, keys: dict[str, str], proxy: dict[str, str] | None) -> str:
    text = existing
    if not text.strip():
        text = f"# LogsTotal {role} .env for {entry} — generated by ./logstotal deploy:env.\n# Hand-added keys are preserved when this is regenerated; managed keys are not.\n{MARKER}\n"
    for key, value in keys.items():
        text = set_key(text, key, value)
    if proxy:
        text, _ = apply_proxy_settings(text, proxy["domain"], proxy["acme_email"], tls=proxy.get("tls", "acme"))
        # Not part of proxy_enable's six keys: those are the single-host HTTPS switch,
        # while these two describe where the proxy sits relative to the app, which only
        # a deployment knows.
        text = set_key(text, "TRUST_PROXY_HEADERS", "true")
        text = set_key(text, "TRUSTED_PROXY_CIDRS", proxy["trusted_cidrs"])
        if proxy.get("basic_auth_user") and proxy.get("basic_auth_hash"):
            text, _ = apply_basic_auth(text, proxy["basic_auth_user"], proxy["basic_auth_hash"])
    return text


# ── Main ─────────────────────────────────────────────────────────────────────


def build(args: argparse.Namespace) -> int:
    hosts = parse_hosts(args.hosts)
    out_dir = Path(args.out_dir)
    state_path = Path(args.state)

    vpn: dict[str, str] = {}
    addresses_path = Path(args.addresses)
    if addresses_path.exists():
        try:
            vpn = json.loads(addresses_path.read_text(encoding="utf-8")).get("addresses", {})
        except (OSError, ValueError) as exc:
            raise GeneratorError(f"{addresses_path} is not readable JSON ({exc}).") from exc

    addresses, warnings = resolve_addresses(hosts, cp_address=args.cp_address or None, vpn=vpn)
    cp_entry = hosts[0]["entry"]
    cp_address = addresses[cp_entry]
    bind_address = args.cp_bind_address
    if bind_address:
        if not is_ip_literal(bind_address):
            raise GeneratorError(f"--cp-bind-address must be an IP address, not '{bind_address}' — Docker binds ports by address, not by name.")
    else:
        bind_address, bind_warnings = bind_address_for(cp_address)
        warnings.extend(bind_warnings)

    # Checked before anything is written, so a refusal leaves nothing half-applied.
    #
    # Both arms refuse rather than drop the credentials. Continuing would send the control
    # plane out with no HTTP authentication while the operator is told three times that it
    # has some — the run banner says "Basic auth: yes", the hashing step says "hashed", and
    # the smoke check passes because an unauthenticated server ignores the credentials it
    # is handed and answers 200.
    #
    # The no-hash arm matters most, because it is the default state of a RE-RUN:
    # deploy-fleet.sh persists DEPLOY_BASIC_AUTH_USER into deploy.env but deliberately never
    # persists the password, so a second, bare `task deploy` has a username, no password,
    # nothing to hash — and would publish the control plane unauthenticated using the same
    # command that secured it the first time.
    if args.basic_auth_user and not args.domain:
        raise GeneratorError(
            "DEPLOY_BASIC_AUTH_USER is set but DEPLOY_DOMAIN is not. Basic auth is enforced by Caddy, "
            "which only runs with the proxy profile — so nothing would be in front of the control plane. "
            "Set DEPLOY_DOMAIN, or unset DEPLOY_BASIC_AUTH_USER to deploy without it."
        )
    if args.basic_auth_hash and not args.basic_auth_user:
        # docker-caddy-entrypoint.sh refuses to start with only one of the pair, so this
        # would either take the control plane down or, since the generator writes neither
        # without both, quietly publish it unauthenticated. Neither is what was asked for.
        raise GeneratorError("DEPLOY_BASIC_AUTH_HASH is set but DEPLOY_BASIC_AUTH_USER is not. Caddy needs both; set the username, or unset the hash to deploy without basic auth.")
    if args.basic_auth_user and not args.basic_auth_hash:
        raise GeneratorError(
            "DEPLOY_BASIC_AUTH_USER is set but no password or hash came with it, so the control plane "
            "would be published with no authentication. Set DEPLOY_BASIC_AUTH_PASSWORD (it is hashed on "
            "the control plane and never stored), or DEPLOY_BASIC_AUTH_HASH if you hashed it yourself. "
            "Note that a re-run does not remember the password: deploy.env keeps the username, never the "
            "plaintext. Unset DEPLOY_BASIC_AUTH_USER to deploy without basic auth."
        )

    seeds = [out_dir / f"{hosts[0]['slug']}.env", out_dir / "control-plane.env", Path(args.seed_from)]
    state = load_state(state_path)
    secrets_map, sources = resolve_secrets(state=state, seed_files=seeds, force=args.force)
    write_state(state_path, secrets_map)

    proxied = bool(args.domain)
    proxy = None
    if proxied:
        proxy = {
            "domain": args.domain,
            "tls": args.proxy_tls,
            # Only `acme` ever contacts a CA, so only `acme` needs a default invented.
            "acme_email": args.acme_email or (f"admin@{args.domain}" if args.proxy_tls == "acme" else ""),
            "trusted_cidrs": args.trusted_proxy_cidrs,
            "basic_auth_user": args.basic_auth_user or "",
            "basic_auth_hash": args.basic_auth_hash or "",
        }

    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for index, host in enumerate(hosts):
        target = out_dir / f"{host['slug']}.env"
        existing = target.read_text(encoding="utf-8") if target.exists() else ""
        if host["role"] == "control-plane":
            keys = control_plane_keys(secrets_map, admin_email=args.admin_email, bind_address=bind_address, proxied=proxied, proxy_tls=args.proxy_tls)
            body = render_host_env(existing, role=host["role"], entry=host["entry"], keys=keys, proxy=proxy)
        else:
            keys = worker_keys(
                secrets_map,
                cp_address=cp_address,
                name=worker_name(host["entry"], index),
                address=addresses[host["entry"]],
                huey_workers=args.huey_workers,
            )
            body = render_host_env(existing, role=host["role"], entry=host["entry"], keys=keys, proxy=None)
        target.write_text(body, encoding="utf-8")
        target.chmod(0o600)
        label = host["role"] if host["role"] == "control-plane" else keys["WORKER_NAME"]
        written.append(f"  {target}  ({label})")

    print(f"Secrets: {', '.join(sources)} → {state_path}")
    print(f"Control plane reachable at: {cp_address}  (relays bound to {bind_address})")
    for line in written:
        print(line)
    # Flush first: stdout is block-buffered when piped and stderr is not, so without
    # this the warnings surface *above* the report they are qualifying.
    sys.stdout.flush()
    for warning in warnings:
        print(f"WARN: {warning}", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate one .env per LogsTotal fleet host")
    parser.add_argument("--hosts", required=True, help="comma-separated host list; the first is the control plane")
    parser.add_argument("--out-dir", default=DEFAULT_OUT_DIR)
    parser.add_argument("--state", default=DEFAULT_STATE, help="where the shared secrets are remembered")
    parser.add_argument("--addresses", default=DEFAULT_ADDRESSES, help="VPN address map written by ./logstotal deploy:vpn")
    parser.add_argument("--cp-address", default="", help="address workers use to reach the control plane")
    parser.add_argument(
        "--cp-bind-address", default="", help="IP the control plane binds its Redis/PG/S3 relays to (default: the control-plane address when it is an IP, else 0.0.0.0)"
    )
    parser.add_argument("--seed-from", default=".env", help="existing env file to take shared secrets from on first run")
    parser.add_argument("--admin-email", default="admin@example.com")
    parser.add_argument("--huey-workers", type=int, default=4)
    parser.add_argument("--domain", default="", help="setting this turns the Caddy/HTTPS proxy on")
    parser.add_argument("--acme-email", default="")
    parser.add_argument(
        "--proxy-tls",
        default="acme",
        choices=["acme", "internal", "custom", "off"],
        help="how the control plane's Caddy terminates TLS (default: acme)",
    )
    parser.add_argument("--trusted-proxy-cidrs", default="172.18.0.0/16")
    parser.add_argument("--basic-auth-user", default="")
    parser.add_argument("--basic-auth-hash", default="", help="bcrypt hash; never the plaintext")
    parser.add_argument("--force", action="store_true", help="regenerate every shared secret — logs every session out")
    args = parser.parse_args(argv)
    try:
        return build(args)
    except GeneratorError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
