#!/usr/bin/env bash
# Multi-server .env scaffolder for LogsTotal (developer / ops).
#
# Generates deploy-envs/control-plane.env and deploy-envs/worker.env from
# deployment-ready defaults, reusing SECRET_KEY/ADMIN_EMAIL from .env when
# present and auto-generating any missing secrets. The `proxy` action layers
# Caddy/HTTPS defaults onto the already-generated control-plane.env.
#
# Usage:
#   bash scripts/deploy-env-scaffold.sh          # generate both env templates
#   bash scripts/deploy-env-scaffold.sh proxy    # apply Caddy/HTTPS defaults
#
# The deploy-envs/ directory is gitignored — never commit env files with secrets.
# The secret one-liners are deliberate venv-free `python3 -c` calls (no pdm /
# gen_secrets) so scaffolding works on a bare host. No pipefail — the .env greps
# rely on a non-zero status not aborting the script. Assumes the repo root is the
# current working directory.

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

# ── scaffold (was: task deploy:env-scaffold) ──────────────────────────────────

do_scaffold() {
  # Regenerating over an existing scaffold rotates SECRET_KEY, POSTGRES_PASSWORD and
  # the S3 keys — which logs every session out and leaves the workers authenticating
  # against a database and bucket with the old credentials. Only values present in a
  # local .env are carried over, so hand-edits to deploy-envs/ would be lost silently.
  local existing=""
  for f in deploy-envs/control-plane.env deploy-envs/worker.env; do
    [ -f "$f" ] && existing="${existing} ${f}"
  done
  if [ -n "$existing" ] && [ "${FORCE:-}" != "yes" ]; then
    die "refusing to overwrite existing env scaffold ($(echo "$existing" | tr -s ' ')).
These hold generated secrets — regenerating rotates them. Edit the files in place,
or override with: FORCE=yes ./logstotal deploy:env-scaffold"
  fi

  mkdir -p deploy-envs

  # ── Control plane env ──
  if [ -f .env ]; then
    SK=$(grep -E "^SECRET_KEY=" .env | head -1 | sed 's/^SECRET_KEY=//')
    AE=$(grep -E "^ADMIN_EMAIL=" .env | head -1 | sed 's/^ADMIN_EMAIL=//')
    AP=$(grep -E "^ADMIN_PASSWORD=" .env | head -1 | sed 's/^ADMIN_PASSWORD=//')
    PGPW=$(grep -E "^POSTGRES_PASSWORD=" .env | head -1 | sed 's/^POSTGRES_PASSWORD=//')
    RPW=$(grep -E "^REDIS_PASSWORD=" .env | head -1 | sed 's/^REDIS_PASSWORD=//')
    S3AK=$(grep -E "^S3_ACCESS_KEY=" .env | head -1 | sed 's/^S3_ACCESS_KEY=//')
    S3SK=$(grep -E "^S3_SECRET_KEY=" .env | head -1 | sed 's/^S3_SECRET_KEY=//')
    GRPC=$(grep -E "^GARAGE_RPC_SECRET=" .env | head -1 | sed 's/^GARAGE_RPC_SECRET=//')
    GADM=$(grep -E "^GARAGE_ADMIN_TOKEN=" .env | head -1 | sed 's/^GARAGE_ADMIN_TOKEN=//')
  fi
  SK="${SK:-$(python3 -c 'import secrets; print(secrets.token_hex(32))' 2>/dev/null || echo 'GENERATE-ME')}"
  AE="${AE:-admin@example.com}"
  AP="${AP:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))' 2>/dev/null || echo 'CHANGE-ME')}"
  PGPW="${PGPW:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))' 2>/dev/null || echo 'CHANGE-ME')}"
  RPW="${RPW:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))' 2>/dev/null || echo 'CHANGE-ME')}"
  S3AK="${S3AK:-$(python3 -c 'import secrets; print("GK"+secrets.token_hex(12))' 2>/dev/null || echo 'GENERATE-GK-KEY')}"
  S3SK="${S3SK:-$(python3 -c 'import secrets; print(secrets.token_hex(32))' 2>/dev/null || echo 'GENERATE-64-HEX')}"
  if ! printf "%s" "$S3AK" | grep -qE '^GK[0-9a-f]{24}$'; then
    S3AK=$(python3 -c 'import secrets; print("GK"+secrets.token_hex(12))' 2>/dev/null || echo 'GENERATE-GK-KEY')
  fi
  # Garage refuses an RPC secret that is not 32 bytes of hex, so a bad value is replaced.
  if ! printf "%s" "${GRPC:-}" | grep -qE '^[0-9a-f]{64}$'; then
    GRPC=$(python3 -c 'import secrets; print(secrets.token_hex(32))' 2>/dev/null || echo 'GENERATE-64-HEX')
  fi
  GADM="${GADM:-$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))' 2>/dev/null || echo 'CHANGE-ME')}"
  if ! printf "%s" "$S3SK" | grep -qE '^[0-9a-f]{64}$'; then
    S3SK=$(python3 -c 'import secrets; print(secrets.token_hex(32))' 2>/dev/null || echo 'GENERATE-64-HEX')
  fi

  cat > deploy-envs/control-plane.env <<CPEOF
# LogsTotal control-plane .env (generated by ./logstotal deploy:env-scaffold)
SECRET_KEY=${SK}
ADMIN_EMAIL=${AE}
ADMIN_PASSWORD=${AP}

# Docker profiles: postgres + s3 (Garage) + workers (expose Redis/PG/S3)
COMPOSE_PROFILES=postgres,s3,workers
POSTGRES_PASSWORD=${PGPW}

# S3 storage (required for multi-server)
STORAGE_BACKEND=s3
S3_BUCKET=logstotal
S3_ACCESS_KEY=${S3AK}
S3_SECRET_KEY=${S3SK}
S3_REGION=logstotal
# The bundled Garage's own secrets (docker-compose.yml passes them to it).
GARAGE_RPC_SECRET=${GRPC}
GARAGE_ADMIN_TOKEN=${GADM}

# Redis
REDIS_PASSWORD=${RPW}

# Expose services on VPN IP (change to your WireGuard/Tailscale IP)
REDIS_EXPOSE=10.0.0.1:6379
POSTGRES_EXPOSE=10.0.0.1:5432
GARAGE_EXPOSE=10.0.0.1:3900

# Cookies. A multi-server control plane is usually reached over plain HTTP on the VPN
# until Caddy is put in front of it, and the auth cookie is Secure-flagged by default —
# so login silently succeeds server-side and the browser drops the cookie, which reads as
# "the password is wrong".
# Set to true ONLY while the control plane is served over http://. Comment it out (or set
# false) the moment TLS is in front — ./logstotal deploy:env-scaffold:proxy does that for you.
COOKIE_INSECURE=true
CPEOF
  ok "created $(value deploy-envs/control-plane.env)"

  # ── Worker env ──
  cat > deploy-envs/worker.env <<WEOF
# LogsTotal worker .env (generated by ./logstotal deploy:env-scaffold)
SECRET_KEY=${SK}
WORKER_NAME=worker-01
WORKER_IP=10.0.0.2

# Point at control plane services (change IPs to match your VPN)
DATABASE_URL=postgresql+asyncpg://logstotal:${PGPW}@10.0.0.1:5432/logstotal
SYNC_DATABASE_URL=postgresql+psycopg2://logstotal:${PGPW}@10.0.0.1:5432/logstotal
REDIS_URL=redis://:${RPW}@10.0.0.1:6379

# S3 storage
STORAGE_BACKEND=s3
S3_ENDPOINT=http://10.0.0.1:3900
S3_BUCKET=logstotal
S3_ACCESS_KEY=${S3AK}
S3_SECRET_KEY=${S3SK}
S3_REGION=logstotal

HUEY_WORKERS=4
WEOF
  ok "created $(value deploy-envs/worker.env)"

  # ── Validate: no placeholder/empty secrets should survive scaffolding ──
  PROBLEMS=0
  for f in deploy-envs/control-plane.env deploy-envs/worker.env; do
    BAD=$(grep -nE '(CHANGE-ME|GENERATE-ME|GENERATE-GK-KEY|GENERATE-64-HEX|change-me|set-a-strong-password)' "$f" | head -5 || true)
    if [ -n "$BAD" ]; then
      warn "${f} still contains placeholder values (no python3 on this host?):"
      printf '%s\n' "$BAD" | sed 's/^/    /'
      PROBLEMS=$((PROBLEMS + 1))
    fi
  done
  if [ "$PROBLEMS" -eq 0 ]; then
    ok "no placeholder secrets remain in the generated files"
  fi

  banner_open
  printf '  Next steps:\n'
  printf '    1. Edit both files — set real host IPs (10.0.0.1/10.0.0.2 are examples) and review every value.\n'
  printf '    2. Copy to hosts:\n'
  printf '         scp deploy-envs/control-plane.env root@cp:/opt/logstotal/.env\n'
  printf '         scp deploy-envs/worker.env root@worker:/opt/logstotal/.env\n'
  printf '    3. ./logstotal deploy:preflight                                  # SSH + tools check\n'
  printf '    4. ./logstotal deploy   # first deploy\n'
  printf '       (existing deployment upgrading versions: ./logstotal upgrade)\n'
  printf '    5. ./logstotal deploy:smoke                                      # verify health\n'
  printf '\n'
  printf '  For Caddy/HTTPS in control-plane.env, run: ./logstotal deploy:env-scaffold:proxy\n'
  banner_close
}

# ── proxy (was: task deploy:env-scaffold:proxy inline block) ──────────────────

do_proxy() {
  if [ ! -f deploy-envs/control-plane.env ]; then
    die "deploy-envs/control-plane.env not found."
  fi

  sed -i.bak 's/^COMPOSE_PROFILES=.*/COMPOSE_PROFILES=postgres,s3,proxy,workers/' deploy-envs/control-plane.env && rm -f deploy-envs/control-plane.env.bak

  # The base scaffold sets COOKIE_INSECURE=true because a fresh control plane is reached
  # over plain HTTP on the VPN. Putting Caddy in front is exactly the moment that stops
  # being true, and leaving it set would keep the auth cookie unflagged behind TLS.
  if grep -qE '^COOKIE_INSECURE=' deploy-envs/control-plane.env; then
    sed -i.bak 's/^COOKIE_INSECURE=.*/COOKIE_INSECURE=false/' deploy-envs/control-plane.env && rm -f deploy-envs/control-plane.env.bak
    ok "COOKIE_INSECURE=false (TLS now terminates at Caddy)"
  fi

  if ! grep -qE '^DOMAIN=' deploy-envs/control-plane.env; then
    {
      printf '\n'
      printf '# ── Caddy / HTTPS proxy settings (added by ./logstotal deploy:env-scaffold:proxy) ──\n'
      printf 'DOMAIN=logs.example.com\n'
      printf '\n'
      printf '# How Caddy terminates TLS: acme (public domain + Lets Encrypt), internal\n'
      printf '# (Caddys own CA - no DNS, no port 80, no internet), custom (your certificate\n'
      printf '# from ./certs), or off (plain HTTP). See docs/install/https.md.\n'
      printf '# With internal or off, set ENABLE_HSTS=false below; with off, also set\n'
      printf '# COOKIE_INSECURE=true or login silently fails.\n'
      printf 'PROXY_TLS=acme\n'
      printf 'ACME_EMAIL=admin@example.com\n'
      printf '\n'
      printf '# Keep the app private; Caddy is the only public entrypoint.\n'
      printf 'WEB_PORT=127.0.0.1:8000:8000\n'
      printf 'TRUST_PROXY_HEADERS=true\n'
      printf 'TRUSTED_PROXY_CIDRS=172.18.0.0/16\n'
      printf 'ENABLE_HSTS=true\n'
      printf '\n'
      printf '# Optional Caddy basic auth (set BASIC_AUTH_HASH if you want this).\n'
      printf 'BASIC_AUTH_USER=\n'
      printf 'BASIC_AUTH_HASH=\n'
    } >> deploy-envs/control-plane.env
  fi

  ok "updated $(value deploy-envs/control-plane.env) with proxy defaults"
  info "set DOMAIN/ACME_EMAIL before deploy"
}

# ── Main ──────────────────────────────────────────────────────────────────────

main() {
  case "${1:-}" in
    "")    do_scaffold ;;
    # `proxy` scaffolds only when there is nothing to apply the defaults to: do_scaffold
    # REFUSES over an existing scaffold (it would rotate every secret), so scaffolding
    # unconditionally would fail on every run after the first — exactly when an operator
    # reaches for it, since do_scaffold's own closing line says to run it next.
    proxy)
      [ -f deploy-envs/control-plane.env ] || do_scaffold
      do_proxy
      ;;
    *)
      echo "Usage: bash scripts/deploy-env-scaffold.sh [proxy]" >&2
      exit 1
      ;;
  esac
}

main "$@"
